#!/bin/bash

echo 'Listening on 443...'
socat OPENSSL-LISTEN:443,cert=/etc/letsencrypt/live/www.johnrcooper.com/fullchain.pem,key=/etc/letsencrypt/live/www.johnrcooper.com/privkey.pem,verify=0,fork,reuseaddr EXEC:"bash handle_connection" 
